const Catalog = [
  [
    {
      id: '1elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-1.jpg',
      name: 'Colorful sneakers',
      price: '$ 67.24',
      descr: 'Famed for its iconic skate shoes, Vans was born in Sixties California and Vans combines fashion and function to create the ultimate in stylish trainers. ',
    },
    {
      id: '2elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-2.jpg',
      name: 'Biker jacket',
      price: '$ 41.55',
      descr: 'Oversized shirt jacket in cotton corduroy. Collar, buttons at front, and yoke at back. Chest pockets with flap and button, diagonal welt front pockets, dropped shoulders, and long sleeves with button at cuffs. Short slits at sides and slightly longer hem at back. Unlined.',
    },
    {
      id: '3elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-3.jpg',
      name: 'Blue sneakers',
      price: '$ 40.00',
      descr: 'Sneakers with lacing at front. Fabric lining, fabric insoles, and rubber soles. Sneakers in faux leather with a graphic design. Elasticized lacing at front and a loop at back. Fabric lining, fabric insoles, and patterned rubber soles.',
    },
    {
      id: '4elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-4.jpg',
      name: 'Textured jacket',
      price: '$ 120.99',
      descr: 'Oversized biker jacket in faux leather with faux shearling lining and large, notched lapels with faux shearling lining. Diagonal zipper at front and removable belt at hem. Faux shearling trim at cuffs and hem.',
    },
    {
      id: '5elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-5.jpg',
      name: 'T-shirt',
      price: '$ 87.50',
      descr: 'Crew-neck T-shirt in soft cotton jersey. Classic T-shirt in soft cotton jersey with a printed design. Dropped shoulders and ribbed neckline.',
    },
    {
      id: '6elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-6.jpg',
      name: 'Scarf',
      price: '$ 60.50',
      descr: 'Scarf in soft woven fabric with fringe at short sides. Soft, cable-knit tube scarf with ribbing at upper and lower edges. Set with a hat and tube scarf in soft cotton jersey.',
    },
  ],
  [
    {
      id: '7elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-7.jpg',
      name: 'Leather bag',
      price: '$ 175.60',
      descr: 'Small shoulder bag in woven fabric with faux leather details. Zipper at top and detachable, adjustable fabric shoulder strap. One outer compartment with zipper and one inner compartment. Lined. Depth 2 1/2 in., height 5 in., width 7 1/2 in.',
    },
    {
      id: '8elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/banner/banner-2.jpg',
      name: 'Sunglasses',
      price: '$ 1.99',
      descr: 'Sunglasses with metal and plastic frames and UV-protective, tinted lenses. Founded in 2005 by Hamilton Remes, sunglasses brand Jeepers Peepers has gained a cult following with its directional collection of vintage-inspired designs. Featuring classic aviator and wayfarer styles reworked with a modern twist, expect a range of bright colours, plastic frames and retro details.',
    },
    {
      id: '9elem',
      img: 'https://colorlib.com/preview/theme/estore/assets/img/categori/product2.png',
      name: 'Green hudi',
      price: '$ 140.00',
      descr: 'Calf-length, turtleneck dress in a soft knit with wool content. Long raglan sleeves, short slits at sides, and ribbing at neck, cuffs, and hem.',
    },
    {
      id: '10elem',
      img: 'https://colorlib.com/preview/theme/estore/assets/img/categori/product3.png',
      name: 'Yellow sweater',
      price: '$ 189.99',
      descr: 'Oversized sweatshirt in a cotton blend. Round neckline, dropped shoulders, and long puff sleeves. Snug, ribbed cuffs, ribbed hem, and brushed inside. Polyester content is recycled.',
    },
    {
      id: '11elem',
      img: 'https://colorlib.com/preview/theme/estore/assets/img/categori/product4.png',
      name: 'Shirt',
      price: '$ 48.00',
      descr: 'Oversized shirt jacket in cotton corduroy. Collar, buttons at front, and yoke at back. Chest pockets with flap and button, diagonal welt front pockets, dropped shoulders, and long sleeves with button at cuffs. Short slits at sides and slightly longer hem at back. Unlined.',
    },
    {
      id: '12elem',
      img: 'https://colorlib.com/preview/theme/estore/assets/img/categori/product6.png',
      name: 'Jacket',
      price: '$ 70.30',
      descr: 'Jacket in faux suede with faux leather details. Collar with tabs and metal buckles, zip at front, and front pockets with zip. Faux shearling lining.',
    },
  ],
  [
    {
      id: '13elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/product/product-8.jpg',
      name: 'Blue polo',
      price: '$ 15.50',
      descr: 'Short-sleeved polo shirt in soft jersey with a collar and button placket. Polo shirt in cotton piqué. Ribbed collar, two buttons at top, saddle shoulders, and short sleeves with ribbed trim. Muscle Fit – designed to showcase the body’s natural physique. Narrow shoulders and tapered sleeves for a flattering silhouette.',
    },
    {
      id: '14elem',
      img: 'https://colorlib.com/preview/theme/malefashion/img/banner/banner-3.jpg',
      name: 'Leather boots',
      price: '$ 99.99',
      descr: 'Platform boots in faux leather with decorative welt seams. Lacing at front, zipper at one side, and loop at back. Chunky soles. Sole thickness 1 3/4 in. Heel height 2 in.',
    },
    {
      id: '15elem',
      img: 'https://colorlib.com/preview/theme/estore/assets/img/categori/product1.png',
      name: 'Colorful shorts',
      price: '$ 25.00',
      descr: 'Sweatshorts in a cotton blend. Elasticized waistband with drawstring, side pockets, and an open back pocket. Raw, rolled-edge hems.',
    },
    {
      id: '16elem',
      img: 'https://colorlib.com/preview/theme/estore/assets/img/categori/product5.png',
      name: 'Sport trousers',
      price: '$ 35.99',
      descr: 'Suit pants in woven fabric with an adjustable elasticized waistband and zip fly with button. Side pockets, mock back pocket, and legs with creases.',
    },
  ],
];
